meta_name: "Foodie Planner"
meta_title: "Plan your meals"
meta_description: "Streamline your meal planning and grocery shopping with our app! Save your favorite recipes on the weekly calendar, generate customized menus, and automatically create a shopping list based on your selections. Simplify your culinary organization and save valuable time with our meal planning and grocery app. Use now and bring your delicious culinary ideas to life!"
meta_image: "cover.png" # should exist in `app/assets/images/`

